server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/games
    username: postgres
    password: diogenes
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    function:
      definition:
    stream:
      default-binder: kafka_default
      bindings:
        gameBinding-out-0:
          destination: event.game-created
          binder: kafka_default
          useNativeDecoding: true
      binders:
        kafka_default:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    default:
                      conmsumer:
                        configuration:
                          session.timeout.ms: 10000
                          max.poll.records: 10
                      producer:
                        compressiontype: gzip
                        configuration:
                          max.request.size: 1000000
                      binder:
                        autoAddPartitions: true
                        autoCreateTopics: true
                        requiredAcks: -1
                        minPartitionCount: 3
                        replicationFactor: 1
                        serdeError: logAndContinue
                        broker: localhost:9092


