server:
  port: 8081

jwt:
  secret: rVubshZyysGb+5lw+tiwcaEFiGpdggfm5I2aey0+Tqh6gqQXGIzhcd/AhocAuJyT2UScLjOHC+NXSj3+Je1rJA==

spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/auth
      username: postgres
      password: diogenes
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

      springdoc:
        api-docs:
          path: /v3/api-docs
        swagger-ui:
          path: /swagger-ui.html


