server:
  port: 8082

jwt:
  secret: dDIFLIVHsCgDakpmjhoNHc5InstUeY9p8RfJLND7MnNL1LHIAABRji1bDSFCI6/sKwU7Di57J2IhENMDeva6rg==

spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8081
          predicates:
            - Path=/v1/auth/**
        - id: game-route
          uri: http://localhost:8080
          predicates:
            - Path=/v1/games/**
          filters:
            - AuthenticationFilter

