server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}

spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: game-route
          uri: http://localhost:8080
          predicates:
            - Path=/games/**
          filter:
            - AuthenticationFilter
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      gateway:
        enabled: true
