server:
  port: 8082

jwt:
  secret: tDRRl8rqyhx05TfgfrQXBgI4qsJkGiuPGo6FwhSSKHO5eeR/emr5pOTV2GqpQG6RLCB/Ey4eAzUEcBQ33VY5Ng==

spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8081
          predicates:
            - Path=/v1/auth/**
          filters: AuthenticationFilter
        - id: game-route
          uri: http://localhost:8080
          predicates:
            - Path=/v1/games/**
          filters:
            - AuthenticationFilter

